# TEXT CONFIG
text:
    name: 'distilroberta-base'
    max_len: 77
    out_size: 768

# AUDIO CONFIG
audio:
    name: 'Cnn14'
    pretrained_abs_path: '/home/fs72538/leona/Custom-CLAP/clap/model/layers/audio_encoders/pretrained_audio_encoders/Cnn14_mAP=0.431.pth'
    sampling_rate: 44100
    duration: 10
    use_fusion: true
    window_size: 1024
    hop_size: 320
    mel_bins: 64
    f_min: 50
    f_max: 14000
    num_classes: 527 # AudioSet classes
    out_size: 2048

# PROJECTION CONFIG 
projection:
    hidden_size: 1024
    out_size: 1024

# TRAINING AND EVALUATION CONFIG
training:
    learning_rate: 0.0001
    batch_size: 256
    stage1_epochs: 20
    stage2_epochs: 20
    betas: [0.9, 0.99]
    weight_decay: 0
    warmup_steps: 300
    milestones: [300]
    seed: 4201452944

# AUDIO CLASSIFIER CONFIG
classifier:
    in_dim: 1024
    out_dim: 50 # ESC50 classes
    act_fn: null
    freeze_text: true
    freeze_audio: false

# FINE-TUNING CONFIG
fine-tuning:
    learning_rate: 0.0001
    batch_size: 64
    epochs: 5
    betas: [0.9, 0.99]
    weight_decay: 0
    warmup_steps: 31
    milestones: [31]
    seed: null
