# TEXT CONFIG
text:
    name: 'distilroberta-base'
    max_len: 77
    out_size: 768

# AUDIO CONFIG
audio:
    name: 'Cnn14'
    pretrained_path: 'clap/model/layers/audio_encoders/cnn14/Cnn14_mAP=0.431.pth'
    sampling_rate: 44100
    duration: 10
    use_fusion: True
    window_size: 1024
    hop_size: 320
    mel_bins: 64
    f_min: 50
    f_max: 14000
    num_classes: 527 # AudioSet classes. Not useful for me as I do not utilize the classification output of the audio encoder.
    out_size: 2048

# PROJECTION CONFIG 
projection:
    hidden_size: 1024
    out_size: 1024
    # temperature: 0.003 IDK what to do with it yet.

# TRAINING AND EVALUATION CONFIG
learning_rate: 0.0001
batch_size: 64
epochs: 5
