# TEXT CONFIG
text:
    name: 'gpt2'
    max_len: 77
    out_size: 768

# AUDIO CONFIG
audio:
    name: 'htsat-tiny'
    pretrained_abs_path: 'C:\Users\leon\Documents\ML_Projects\Custom-CLAP\clap\model\layers\audio_encoders\pretrained_audio_encoders\HTSAT_AudioSet_Saved_6.ckpt'
    sampling_rate: 48000
    duration: 10
    use_fusion: True
    window_size: 1024
    hop_size: 480
    mel_bins: 64
    f_min: 50
    f_max: 14000
    num_classes: 527 # AudioSet classes. Not useful for me as I do not utilize the classification output of the audio encoder.
    depths: [2, 2, 6, 2]
    embed_dim: 96
    out_size: 768

# PROJECTION CONFIG 
projection:
    hidden_size: 1024
    out_size: 1024

# TRAINING AND EVALUATION CONFIG
training:
    learning_rate: 0.0001
    batch_size: 64
    epochs: 5
