# TEXT CONFIG
text:
    name: 'gpt2'
    max_len: 77
    out_size: 768

# AUDIO CONFIG
audio:
    name: 'htsat-tiny'
    pretrained_path: 'clap/model/layers/audio_encoders/htsat/HTSAT_AudioSet_Saved_1.ckpt'
    sampling_rate: 32000
    duration: 10
    use_fusion: True
    window_size: 1024
    hop_size: 320
    mel_bins: 64
    f_min: 50
    f_max: 14000
    num_classes: 527 # AudioSet classes. Not useful for me as I do not utilize the classification output of the audio encoder.
    depths: [2, 2, 6, 2]
    embed_dim: 96
    out_size: 768

# PROJECTION CONFIG 
projection:
    hidden_size: 1024
    out_size: 1024
    # temperature: 0.003 IDK what to do with it yet.

# TRAINING AND EVALUATION CONFIG
learning_rate: 0.0001
batch_size: 64
epochs: 5
