# TEXT ENCODER CONFIG
text_encoder:
    name: 'roberta'
    max_len: 77
    out_size: 768

# AUDIO ENCODER CONFIG
audio_encoder:
    name: 'Cnn14'
    pretrained_path: 'C:/Users/leon/Documents/ML_Projects/Custom-CLAP/clap/models/audio_encoders/cnn14/Cnn14_mAP=0.431.pth'
    sampling_rate: 44100
    window_size: 1024
    hop_size: 320
    mel_bins: 64
    f_min: 50
    f_max: 14000
    # n_fft: 1028 Idk what to do with it yet.
    classes_num: 527 # AudioSet classes. Not useful for me as I do not utilize the classification output of the audio encoder.
    out_size: 2048

# PROJECTION CONFIG 
projection:
    hidden_size: 1024
    out_size: 1024
    # temperature: 0.003 Idk what to do with it yet.

# TRAINING AND EVALUATION CONFIG
batch_size: 1024
duration: 5
